pipelines:
  - name: test_Jenkins
    steps:
      - name: testStepJenkins
        type: Jenkins
        configuration:
          jenkinsJobName: testPipeline
          buildParameters:
            foo1: bar1
            foo2: bar2  
          integrations:
            - name: jenkins
