# pipelines:
#   - name: testJenkinsTrigger
#     steps:
#       - name: testStepJenkins
#         type: Jenkins
#         configuration:
#           jenkinsJobName: sampleJob  
#           integrations:
#             - name: S_B_Jenkins

# pipelines:
#   - name: testJenkinsTrigger
#     steps:
#       - name: testStepJenkins
#         type: Jenkins
#         configuration:
#           jenkinsJobName: foo/job
#           integrations:
#             - name: S_B_Jenkins

pipelines:
  - name: testJenkinsTrigger
    steps:
      - name: testStepJenkins
        type: Jenkins
        configuration:
#           jenkinsJobName: foo/bar/multiBranch  
          jenkinsJobName: foo_multibranch
          jenkinsBranchName: jenkin1
#           jenkinsJobName: var/etc/pipeline
#           jenkinsJobName: testPipeline
#           timeoutSeconds: 1
#           jenkinsJobName: var_freestyle_proj
#           buildParameters:
#            runNumber: 1
#            imageName: test
#            imageTag: test
          integrations:
            - name: S_B_Jenkins

# pipelines:
#   - name: S_B_Jen
# #     configuration:
# #       nodePool: u20dynamic
#     steps:
#       - name: S_B_Jen_step
#         type: Jenkins
#         configuration:
# #           jenkinsJobName: testPipeline 
#           jenkinsJobName: validate
# #           jenkinsJobName: var_freestyle_proj
# #           timeoutSeconds: 1
# #           buildParameters:
# #             run1: 'test1frombash'
# # #             run2: ${run_number}
# #             run2: 100
#           buildParameters:
#             project_name: "${project_name}"
#             project_id: "${project_id}"
#             project_key: "${project_key}"
#             step_url: "${step_url}"
# #             imageName: ${res_app_docker_imageName}
# #             imageTag: ${res_app_docker_imageTag}
# #             environment: "test"
#           integrations:
#             - name: S_B_Jenkins



pipelines:
  - name: S_B_Jen_pipelines
    steps:
      - name: S_B_Jen
        type: Jenkins
        configuration:
          jenkinsJobName: testPipeline
          integrations:
            - name: S_B_Jenkins
      - name: S_B_Jen_0001
        type: Jenkins
        configuration:
          priority: 10000
          inputSteps: 
            - name: S_B_Jen
          jenkinsJobName: testPipeline
          integrations:
            - name: S_B_Jenkins
      - name: S_B_Jen_0002
        type: Jenkins
        configuration:
          priority: 0
          inputSteps: 
            - name: S_B_Jen
          jenkinsJobName: testPipeline
          integrations:
            - name: S_B_Jenkins
